### ISSUE TITLE
Only apply NonNullableListInspection to output types

### ISSUE THREAD

**Issue by spawnia** [worksome/graphlint#7]
I ran an inspection on our schema and added `NonNullableListInspection`. It found many issues in our schema where non-nullable lists are used in input types, which I think is fine and not against the spirit of the rule:

```diff
 input UpdateWgsSvEventHasMany {
-  create: [CreateWgsSvEventInput!]
-  update: [UpdateWgsSvEventInput!]
-  delete: [ID!]
+  create: [CreateWgsSvEventInput!]!
+  update: [UpdateWgsSvEventInput!]!
+  delete: [ID!]!
 }
```

It would be nice if the rule only applied to output types - or were made configurable to allow this.

**Comment by olivernybroe** [comment]
When you say output types you mean things defined with `type` keyword and not with `input` keyword? 

But it's a good point, I think there definitely are cases with `input` which you do want to be nullable.

**Comment by spawnia** [comment]
I refer to output types as opposed to input types according to http://spec.graphql.org/draft/#sec-Input-and-Output-Types. So return types of an `interface` would also count towards output types, whereas field arguments would count towards input types.

**Comment by olivernybroe** [comment]
Ah nice, what not aware of that specification. 
I agree, we should make this configurable and by default not apply it to input types.
